model_name: simple_conv_vae       # Name of the model to use
dataset: cifar10                  # Supported: cifar10, cifar100
batch_size: 128
num_epochs: 10
learning_rate: 1e-3
weight_decay: 1e-5
checkpoint_interval: 2           # Save model every N epochs