model_name: simple_conv_vae
dataset: cifar10
batch_size: 128
num_epochs: 10
learning_rate: 1e-3
weight_decay: 1e-5
checkpoint_interval: 2
resize: [32, 32]     # Resize to (height, width)
color: true          # true = RGB, false = grayscale